export const metadata = {
  title: "Üye Giriş Sayfası & Üye Ol",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <section>{children}</section>;
}
